#%Module1.0
module-whatis "Intel Math Kernel Library"
module-whatis "Version: VERSION"

set intelHome /opt/intel/composer_xe_INTELVERS
prepend-path MANPATH $intelHome/man
prepend-path LD_LIBRARY_PATH $intelHome/mkl/lib/intel64
prepend-path LIBRARY_PATH $intelHome/mkl/lib/intel64
setenv MKL_ROOT $intelHome/mkl
setenv FPATH $intelHome/mkl/include
setenv CPATH $intelHome/mkl/include
setenv NLSPATH $intelHome/mkl/lib/intel64/locale/%l_%t/%N
setenv INCLUDE $intelHome/mkl/include
