NAME           = mkl
VERSION        = 11.2.0.090
RELEASE        = 0
PKGROOT        = /opt/intel

SRC_SUBDIR     = mkl

SOURCE_NAME    = l_mkl
SOURCE_SUFFIX  = tgz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)_$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

TGZ_PKGS       = $(SOURCE_PKG)

RPM.EXTRAS     = AutoReq:No
